import * as Print from 'expo-print';
import * as Sharing from 'expo-sharing';
import * as FileSystem from 'expo-file-system/legacy';
import { Document } from '../types';

/**
 * Generate a multi-page PDF from a document
 */
export const generatePDF = async (document: Document): Promise<string | null> => {
  try {
    console.log('=== PDF GENERATION STARTED ===');
    console.log('Document:', document.name);
    console.log('Pages:', document.pages.length);

    // Create HTML for PDF with all pages
    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1.0">
          <style>
            @page {
              margin: 0;
              size: A4;
            }
            body {
              margin: 0;
              padding: 0;
              font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
            }
            .page {
              page-break-after: always;
              position: relative;
              width: 100%;
              height: 100vh;
              display: flex;
              flex-direction: column;
            }
            .page:last-child {
              page-break-after: auto;
            }
            .header {
              background: #3b82f6;
              color: white;
              padding: 20px;
              text-align: center;
            }
            .page-number {
              background: #3b82f6;
              color: white;
              padding: 10px 20px;
              text-align: center;
              font-size: 14px;
            }
            .image-container {
              flex: 1;
              display: flex;
              align-items: center;
              justify-content: center;
              padding: 20px;
              background: #f9fafb;
            }
            .page-image {
              max-width: 100%;
              max-height: 100%;
              object-fit: contain;
            }
            .first-page {
              background: #3b82f6;
              color: white;
              display: flex;
              flex-direction: column;
              align-items: center;
              justify-content: center;
              text-align: center;
            }
            .first-page h1 {
              font-size: 48px;
              margin: 20px 0;
            }
            .first-page p {
              font-size: 18px;
              opacity: 0.9;
            }
            .metadata {
              margin-top: 30px;
              font-size: 14px;
              opacity: 0.8;
            }
          </style>
        </head>
        <body>
          <!-- Cover Page -->
          <div class="page first-page">
            <div>
              <h1>📄 ${document.name}</h1>
              <p>${document.pages.length} page${document.pages.length !== 1 ? 's' : ''}</p>
              <div class="metadata">
                <p>Created: ${new Date(document.createdAt).toLocaleDateString()}</p>
                <p>Generated by ScanView</p>
              </div>
            </div>
          </div>

          <!-- Document Pages -->
          ${document.pages.map((page, index) => `
            <div class="page">
              <div class="page-number">
                Page ${index + 1} of ${document.pages.length}
              </div>
              <div class="image-container">
                <img 
                  src="file://${page.croppedUri || page.uri}" 
                  class="page-image"
                  alt="Page ${index + 1}"
                />
              </div>
            </div>
          `).join('')}
        </body>
      </html>
    `;

    console.log('HTML content created');

    // Generate PDF
    const { uri } = await Print.printToFileAsync({
      html: htmlContent,
      base64: false,
    });

    console.log('PDF generated at:', uri);

    // Copy to permanent location
    const pdfFileName = `${document.name.replace(/[^a-z0-9]/gi, '_')}_${Date.now()}.pdf`;
    const pdfDirectory = `${FileSystem.documentDirectory}scanview/pdfs/`;
    const pdfPath = `${pdfDirectory}${pdfFileName}`;

    // Ensure directory exists
    const dirInfo = await FileSystem.getInfoAsync(pdfDirectory);
    if (!dirInfo.exists) {
      await FileSystem.makeDirectoryAsync(pdfDirectory, { intermediates: true });
    }

    // Copy PDF to permanent storage
    await FileSystem.copyAsync({
      from: uri,
      to: pdfPath,
    });

    console.log('PDF saved to:', pdfPath);
    console.log('=== PDF GENERATION COMPLETE ===');

    return pdfPath;
  } catch (error) {
    console.error('=== PDF GENERATION ERROR ===');
    console.error(error);
    return null;
  }
};

/**
 * Generate and share PDF
 */
export const generateAndSharePDF = async (document: Document): Promise<boolean> => {
  try {
    const pdfPath = await generatePDF(document);
    
    if (!pdfPath) {
      return false;
    }

    // Check if sharing is available
    const canShare = await Sharing.isAvailableAsync();
    
    if (canShare) {
      await Sharing.shareAsync(pdfPath, {
        mimeType: 'application/pdf',
        dialogTitle: `Share ${document.name}`,
        UTI: 'com.adobe.pdf',
      });
      return true;
    }

    return false;
  } catch (error) {
    console.error('Error sharing PDF:', error);
    return false;
  }
};

/**
 * Generate single page PDF (quick export)
 */
export const generateSinglePagePDF = async (
  imagePath: string,
  fileName: string
): Promise<string | null> => {
  try {
    const htmlContent = `
      <!DOCTYPE html>
      <html>
        <head>
          <meta charset="utf-8">
          <style>
            @page { margin: 0; size: A4; }
            body { margin: 0; padding: 0; }
            img { width: 100%; height: 100vh; object-fit: contain; }
          </style>
        </head>
        <body>
          <img src="file://${imagePath}" alt="Document" />
        </body>
      </html>
    `;

    const { uri } = await Print.printToFileAsync({ html: htmlContent });
    
    const pdfPath = `${FileSystem.documentDirectory}scanview/pdfs/${fileName}.pdf`;
    await FileSystem.copyAsync({ from: uri, to: pdfPath });
    
    return pdfPath;
  } catch (error) {
    console.error('Error generating single page PDF:', error);
    return null;
  }
};